spring.application.name=PaymentAnalytics

# Oracle UAT DB Configuration
#spring.datasource.url=jdbc:oracle:thin:@//10.126.249.232:1881/uatods
#spring.datasource.username=relportal
#spring.datasource.password=relportal
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Oracle PROD DB Configuration
spring.datasource.url=jdbc:oracle:thin:@//10.126.143.58:1881/prodods.reliancecapital.com
spring.datasource.username=relportal
spring.datasource.password=relportal
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.thymeleaf.cache=false
spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html